---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bankapp
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    branch: main
  url: https://github.com/sureshc2024/BankApp-CD-gitops-fluxcd.git
